sudo: required
services:
  - docker
language: generic

cache:
  directories:
  - $HOME/.m2  

before_install:
  - mvn clean install
  - cd ../
  - docker build planpackrepeat-backend
  - gem install bundler
 
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "travelapp"
  env: "TravelAppDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-414657016646"
  bucket_path: "travelapp"
  on:
    branch: master
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
    
after_deploy:
  - echo "App started" 
