language: java
cache:
  directories:
    - $HOME/.m2
script:
  - mkdir build
  - cp target/travelapp-0.0.1-SNAPSHOT.jar build/travelapp.jar  
deploy:
    provider: elasticbeanstalk
    skip_cleanup: true
    app: travelapp
    env: TravelAppDocker-env
    zip_file: 'build/travelapp.jar'
    bucket_name: elasticbeanstalk-us-east-1-414657016646
    region: us-east-1
    access_key_id:
      secure: $ACCESSKEYID
    secret_access_key:
      secure: $SECRETACCESSKEY
    on:
      branch: master
